name: build_uinput

on:
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        unraid_version: [6.10.2, 6.10.1, 6.10.0, 6.9.2]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: addnab/docker-run-action@v3
        with:
          registry: docker.io
          image: gameonwhales/unraid-module-builder:latest
          options: |
            -v ${{ github.workspace }}/packages/uinput/config:/config
            -v ${{ github.workspace }}/packages/uinput/root/:/output
            -e UNRAID_VERSION=${{ matrix.unraid_version }}
          shell: bash
          run: /opt/scripts/build.sh

      - name: get built kernel version
        id: kernel-version
        run: echo "::set-output name=kernel::$(ls ${{ github.workspace }}/packages/uinput/root/lib/modules/)"

      - name: make kernel package
        run: |
          mkdir output
          cd ${{ github.workspace }}/packages/uinput/root/
          chmod +x ${{ github.workspace }}/utils/fmakepkg.sh
          ${{ github.workspace }}/utils/fmakepkg.sh ${{ github.workspace }}/output/uinput-${{ steps.kernel-version.outputs.kernel }}.txz

      - name: Upload kernel modules for ${{ matrix.unraid_version }} - ${{ steps.kernel-version.outputs.kernel }}
        uses: actions/upload-artifact@v2
        with:
          name: uinput-${{ steps.kernel-version.outputs.kernel }}.txz
          path: ${{ github.workspace }}/output/uinput-${{ steps.kernel-version.outputs.kernel }}.txz

      - name: generate checksum (md5)
        id: checksum
        run: md5sum ${{ github.workspace }}/output/uinput-${{ steps.kernel-version.outputs.kernel }}.txz > ${{ github.workspace }}/output/uinput-${{ steps.kernel-version.outputs.kernel }}.txz.md5

      - name: Upload checksum for ${{ steps.kernel-version.outputs.kernel }} (md5)
        uses: actions/upload-artifact@v2
        with:
          name: uinput-${{ steps.kernel-version.outputs.kernel }}.txz.md5
          path: ${{ github.workspace }}/output/uinput-${{ steps.kernel-version.outputs.kernel }}.txz.md5

      - name: generate checksum (sha256)
        id: checksum_sha
        run: sha256sum ${{ github.workspace }}/output/uinput-${{ steps.kernel-version.outputs.kernel }}.txz > ${{ github.workspace }}/output/uinput-${{ steps.kernel-version.outputs.kernel }}.txz.sha256

      - name: Upload checksum for ${{ steps.kernel-version.outputs.kernel }} (sha256)
        uses: actions/upload-artifact@v2
        with:
          name: uinput-${{ steps.kernel-version.outputs.kernel }}.txz.sha256
          path: ${{ github.workspace }}/output/uinput-${{ steps.kernel-version.outputs.kernel }}.txz.sha256

  release:
    needs: docker-build
    runs-on: ubuntu-latest
    steps:
      - name: Download all built kernel modules
        uses: actions/download-artifact@v2
        with:
          path: ${{ github.workspace }}/

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y.%m.%d')"

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ github.workspace }}/**/*"
          tag: modules-${{ steps.date.outputs.date }}
          commit: ${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
